server:
  port: 8010
  
spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev

  jackson:
    serialization:
      fail-on-empty-beans: false