#!/usr/bin/env groovy
pipeline{
    agent none
    stages{
        stage ('Build project'){
            agent{
                docker { 
                    image 'maven' 
                    args '-u root'
                }
            }
            steps{
                dir('customer-service'){
                    sh "mvn package"
                }
            }
            steps{
                dir('customer-service'){
                    sh 'docker build -t customer-service-image:${BUILD_NUMBER} .'
                }
            }
            steps{
                sh "docker stop customer-service-image || true && docker rm customer-service-image || true"
                sh "docker run --name customer-service-image -d -p 8010:8010 customer-service-image:${BUILD_NUMBER}"
            }
        }
    }
}