#!/usr/bin/env groovy
pipeline{
    agent any
    stages{
        stage ('Build .jar file'){
            agent{
                docker { 
                    image 'maven' 
                    args '-u root'
                }
            }
            steps{
                dir('customer-service'){
                    sh "mvn package"
                }
            }
        }
        stage ('Build Docker image'){
            agent none
            steps{
                dir('customer-service'){
                    sh 'docker build -t customer-service-image:${BUILD_NUMBER} .'
                }
            }
        }
        stage ('Refresh container'){
            steps{
                sh "docker stop customer-service-image || true && docker rm customer-service-image || true"
                sh "docker run --name customer-service-image -d -p 8010:8010 customer-service-image:${BUILD_NUMBER}"
            }
        }
    }
}